account/urls.py
from django.urls import path
from account import views

app_name = "account"
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
]

chatbot/urls.py
# urls.py
from django.urls import path
from chatbot import views


app_name = "chatbot"

urlpatterns = [
    path('chatbot/', views.chatbot_view, name='chatbot_view'),
]

recommend/urls.py
from django.urls import path
from recommend import views

app_name = "recommend"

urlpatterns = [
    path('recommend/', views.recommend_view, name='recommend_view'),  # 루트 URL에 대한 뷰 설정
    path('pop_restaurants/', views.load_restaurants, name='load_restaurants'),
    path('recom_customers/<str:model>/', views.load_customers, name='load_customers'),
]

restaurant/urls.py
from django.urls import path
from restaurant import views

app_name = 'restaurant'
urlpatterns = [
    path('restaurant/', views.restaurant_view, name='restaurant_view'),
    path('restaurant/<int:restaurant_id>/', views.restaurant_detail, name='restaurant_detail'),
    path('review/edit/<int:review_id>/', views.edit_review, name='edit_review'),
    path('review/delete/<int:review_id>/', views.delete_review, name='delete_review'),
]

soulfood/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from soulfood import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('account/', include('account.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('chatbot/', include('chatbot.urls')),
    path('recommend/', include('recommend.urls')),
]

if settings.DEBUG: # 미디어 파일 URL 패턴 추가
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<!-- Include the Navbar -->
{% include 'navbar.html' %}

<div class="container">
    <div class="head">
        <div class="title">
            <img src="{% static 'img/SoulFood_logo.png' %}" alt="Soul Food Logo">
        </div>
        <div class="title">안녕하세요, 소울푸드 입니다.
            <br/>어떤 맛집을 찾으시나요?
            <form method="get" action="{% url 'restaurant:restaurant_view' %}">
                <input type="text" name="q" placeholder="찾으시는 식당을 검색해보세요." value="{{ query|default:'' }}">
                <button type="submit">검색</button>
            </form>
        </div>

    </div>
</div>

</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}"> <!-- Include your CSS file -->
</head>
<body>
<nav class="navbar">
    <div class="navbar-container">
        <div class="navbar-left">
            <ul class="navbar-nav">
                <li><a href="{% url 'restaurant:restaurant_view' %}">식당 찾기</a></li>
                <li><a href="{% url 'recommend:recommend_view' %}">식당 추천</a></li>
            </ul>
        </div>
        <a class="navbar-brand" href="{% url 'main' %}">
            <img src="{% static 'img/SF.png' %}" class="brand-img" alt="SF Logo">
        </a>
        <div class="navbar-right">
            <ul class="navbar-nav">
                <li><a href="{% url 'chatbot:chatbot_view' %}" class="chatbot-btn" aria-label="ChatBot"></a></li>
            </ul>
            <div class="navbar-links">
                {% if user.is_authenticated %}
                <div class="navbar-user-info">
                    {% if user.profile_image %}
                    <img src="{{ user.profile_image.url }}" alt="{{ user.username }}'s profile image"
                         class="navbar-profile-image">
                    {% else %}
                    <img src="{% static 'account/img/default_profile.png' %}" alt="Default profile image"
                         class="navbar-profile-image">
                    {% endif %}
                    <span class="navbar-user">Hello, {{ user.username }}!</span>
                </div>
                <a href="{% url 'account:logout' %}" class="navbar-link">Logout</a>
                {% else %}
                <a href="{% url 'account:login' %}" class="navbar-link">Login</a>
                <a href="{% url 'account:signup' %}" class="navbar-link">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

</body>
</html>